apiVersion: skaffold/v4beta6
kind: Config
build:
  artifacts:
  - image: "flow-test"
    context: hack/flow-test
    docker:
      dockerfile: hack/flow-test/Dockerfile
  - image: "hydra"
    custom:
      buildCommand: ./build.sh
      dependencies:
        paths:
          - rockcraft.yaml
    platforms: ["linux/amd64"]
  local:
    push: true

manifests:
  rawYaml:
    - hack/kubectl/iam.yaml

deploy:
  helm:
    releases:
      - name: postgresql
        remoteChart: oci://registry-1.docker.io/bitnamicharts/postgresql
        valuesFiles: ["hack/helm/postgresql.yaml"]
      - name: hydra
        remoteChart: hydra
        repo: https://k8s.ory.sh/helm/charts
        wait: false
        upgradeOnChange: true
        valuesFiles: ["hack/helm/hydra.yaml"]
        setValueTemplates:
          image.repository: "{{.IMAGE_REPO_hydra}}"
          image.tag: "{{.IMAGE_TAG_hydra}}@{{.IMAGE_DIGEST_hydra}}"
      - name: kratos
        remoteChart: kratos
        repo: https://k8s.ory.sh/helm/charts
        valuesFiles: ["hack/helm/kratos.yaml"]
        wait: false
        upgradeOnChange: true

portForward:
  - resourceType: service
    resourceName: hydra-public
    namespace: default
    port: 4444
    localPort: 4444
  - resourceType: service
    resourceName: hydra-admin
    namespace: default
    port: 4445
    localPort: 4445
  - resourceType: service
    resourceName: kratos-admin
    namespace: default
    port: 80
    localPort: 4455
  - resourceType: service
    resourceName: kratos-public
    namespace: default
    port: 80
    localPort: 4433
  - resourceType: service
    resourceName: iam
    namespace: default
    port: 8000
    localPort: 8000
