name: auto-approver
run-name: CI for approving PRs

on:
  push:
    branches:
      - "renovate/**"

jobs:
  autoapprove:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Approve PR
        run: |
          gh pr review --approve || true
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      - name: Enable automerge if required
        if: startsWith(github.ref_name, 'renovate/auto-')
        run: |
          gh pr merge --auto --merge || true
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
