name: CI

on:
  push:
    branches:
     - "main"
    paths:
      - "rockcraft.yaml"
      - ".github/workflows/**.yaml"
  pull_request:
    branches:
     - "*"
  workflow_dispatch:

jobs:
  get-architectures:
    runs-on: ubuntu-latest
    outputs:
      architectures: ${{ steps.parse.outputs.architectures }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Parse platforms from rockcraft.yaml
        id: parse
        run: |
          archs=$(yq -o=json -I=0 '.platforms | keys' rockcraft.yaml)
          echo "Found architectures: $archs"
          echo "architectures=$archs" >> "$GITHUB_OUTPUT"

  build:
    needs: get-architectures
    strategy:
      matrix:
        architecture: ${{ fromJson(needs.get-architectures.outputs.architectures) }}
    uses: canonical/identity-team/.github/workflows/_rock-build.yaml@83e6e76b28b0db96c133c16bbec121cba34a86db # v1.14.3
    with:
      structure-tests-enabled: true
      architecture: ${{ matrix.architecture }}

  gh-publish:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: build
    permissions:
      packages: write
      contents: read
    uses: canonical/identity-team/.github/workflows/_rock-gh-publish-third-party.yaml@83e6e76b28b0db96c133c16bbec121cba34a86db # v1.14.3

  oci-publish:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: build
    uses: canonical/identity-team/.github/workflows/_rock-oci-publish.yaml@83e6e76b28b0db96c133c16bbec121cba34a86db # v1.14.3
    with:
      edge-release: false
      eol-stable-release: "3 month"
    secrets:
      PAT_TOKEN: ${{ secrets.PAT_TOKEN }}

  scan:
    if: ${{ github.ref == 'refs/heads/main' }}
    needs: gh-publish
    permissions:
      security-events: write
      actions: read
      contents: read
      packages: read
    uses: canonical/identity-team/.github/workflows/_rock-scan.yaml@83e6e76b28b0db96c133c16bbec121cba34a86db # v1.14.3
    with:
      image: ${{ needs.gh-publish.outputs.image }}
