# Publish the rock image to ghcr
name: Publish

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4

      - name: Log in to the Container registry
        uses: docker/login-action@1f36f5b7a2d2f7bfd524795fc966e6d88c37baa9
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Use the rockcraft snap to get skopeo because the snap and the apt package on the ubuntu
      # archives are very old. Only rockcraft=latest/edge has a newer skopeo version
      # TODO(nsklikas): Either use rockcraft=latest/stable or install skopeo from apt when one
      # of them is updated
      - name: Install Rockcraft to get skopeo
        run: |
          sudo snap install --classic --channel latest/edge rockcraft

      - name: Install yq
        run: |
          sudo snap install yq

      - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4
        with:
          name: rock

      - name: Import and push to github package
        run: |
          image_name="$(yq '.name' rockcraft.yaml)"
          version="$(yq '.version' rockcraft.yaml)"
          rock_file=$(ls *.rock | tail -n 1)
          sudo rockcraft.skopeo \
            --insecure-policy \
            copy \
            oci-archive:"${rock_file}" \
            docker-daemon:"ghcr.io/canonical/${image_name}:${version}"
          docker push ghcr.io/canonical/${image_name}:${version}
  
  oci-factory:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
      # install oci-factory via golang and set path in environment
      - name: Install oci-factory
        run: |
          sudo apt update && sudo apt install -y golang-go git
          go install github.com/canonical/oci-factory/tools/cli-client/cmd/oci-factory@2cc4d8153a31306cf728482bf4f5d82624aafb51
          GO111MODULE=on go install github.com/mikefarah/yq/v4@v4.44.3
          echo "OCI_FACTORY=$(go env GOPATH)/bin/oci-factory" >> $GITHUB_ENV
          echo "YQ=$(go env GOPATH)/bin/yq" >> $GITHUB_ENV
      - name: Set EOLs and version
        run: |
          echo EOL_STABLE=$(date -d "$(date +'%Y-%m-%d') +6 month" +%Y-%m-%d") >> $GITHUB_ENV
          echo IMAGE_VERSION=$($YQ '.version' rockcraft.yaml) >> $GITHUB_ENV
      - name: Release
        run: |
          $OCI_FACTORY upload -y --release track=$IMAGE_VERSION-22.04,risk=stable,eol=$EOL_STABLE
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}            