# Publish the rock image to ghcr
name: Publish

on:
  workflow_call:

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Log in to the Container registry
        uses: docker/login-action@5d8785b43a795ee002a17dbf1a2235dc1997224b
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Use the rockcraft snap to get skopeo because the snap and the apt package on the ubuntu
      # archives are very old. Only rockcraft=latest/edge has a newer skopeo version
      # TODO(nsklikas): Either use rockcraft=latest/stable or install skopeo from apt when one
      # of them is updated
      - name: Install Rockcraft to get skopeo
        run: |
          sudo snap install --classic --channel latest/edge rockcraft

      - name: Install yq
        run: |
          sudo snap install yq

      - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4
        with:
          name: rock

      - name: Import and push to github package
        run: |
          image_name="$(yq '.name' rockcraft.yaml)"
          version="$(yq '.version' rockcraft.yaml)"
          rock_file=$(ls *.rock | tail -n 1)
          sudo rockcraft.skopeo \
            --insecure-policy \
            copy \
            oci-archive:"${rock_file}" \
            docker-daemon:"ghcr.io/canonical/${image_name}:${version}"
          docker push ghcr.io/canonical/${image_name}:${version}
