# Scan the published rock image and upload the results
name: Scan

on:
  workflow_call:

jobs:
  scan:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4

      - name: Get name and version
        id: image_info
        run: |
          echo "image_name=$(yq '.name' rockcraft.yaml)" >> "$GITHUB_OUTPUT"
          echo "version=$(yq '.version' rockcraft.yaml)" >> "$GITHUB_OUTPUT"

      - name: Scan image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: "ghcr.io/canonical/${{ steps.image_info.outputs.image_name }}:${{ steps.image_info.outputs.version }}"
          format: 'sarif'
          output: 'trivy-results.sarif'

      - name: Upload scan results to GitHub
        uses: github/codeql-action/upload-sarif@04daf014b50eaf774287bf3f0f1869d4b4c4b913 # v2
        with:
          sarif_file: 'trivy-results.sarif'
